### ISSUE TITLE
NAO "Power V6" compatibility

### ISSUE THREAD

**Issue by gogolgrind** [ros-naoqi/naoqi_driver#118]
Hi!

I am wondering does this driver, and whole ros-naoqi package works well with NAO v6?
Unfortunately there is not so many articles and other projects where NAOv6 is used since _it is very new._ 
I want to collect as much as possible information while my NAOv6 is arriving.

Thanks

Konstantin.

**Comment by Pandhariix** [comment]
Hi Konstantin,

The naoqi_driver package works well with NAOv6. Software-wise, you should obtain the same behaviour using naoqi_driver with a V5 or a V6.

Cheers,
Maxime
