### ISSUE TITLE
Body stiffness

### ISSUE THREAD

**Issue by Meli888** [ros-naoqi/naoqi_driver#121]
Hi, is there a service (or topic) for enable/disable body stiffness (or some parts of the robot) ?

**Comment by Pandhariix** [comment]
Hi, to my knowledge you can't set the robot stiffness through ROS.

**Comment by Meli888** [comment]
With Naoqi, you can : http://doc.aldebaran.com/2-8/naoqi/motion/control-stiffness-api.html#ALMotionProxy::setStiffnesses__AL::ALValueCR.AL::ALValueCR
I find another ROS package which did it : http://wiki.ros.org/naoqi_pose

**Comment by Pandhariix** [comment]
> With Naoqi, you can
Absolutely, we just didn't map that feature in naoqi_driver. Although I wasn't familiar with the naoqi_pose package, nice find!
