### ISSUE TITLE
ros in naoV6

### ISSUE THREAD

**Issue by zxvp** [ros-naoqi/naoqi_driver#134]
Hello, I want to use NAOV6 in ROS, but the tutorial on the official website is not suitable. What should I do. Thank you

**Comment by mbusy** [comment]
Hi, which ROS distro are you using? You should install the following packages :
- ros-yourdistro-naoqi-libqi
- ros-yourdistro-naoqi-libqicore
- ros-yourdistro-nao-meshes
- ros-yourdistro-naoqi-bridge-msgs
- ros-yourdistro-naoqi-driver

Those are the "basic packages", allowing you to interact with the NAO (V5 or V6) robot. They have been released for Melodic and for lesser versions (not entirely for Lunar though).

You can then launch the naoqi_driver package to work with your NAO in ROS:
```shell
# You can get your network interface by typing the ifconfig command in your console 
roslaunch naoqi_driver naoqi_driver.launch nao_ip:=your_robot_ip network_interface:=your_interface
```

**Comment by mbusy** [comment]
@zxvp Did you manage to connect your V6 to ROS ?

**Comment by mbusy** [comment]
Closing the issue for lack of activity
