### ISSUE TITLE
when requesting VGA on depth sensor, getting only QQQVGA (80x60)

### ISSUE THREAD

**Issue by laurent-george** [ros-naoqi/naoqi_driver#40]
rostopic echo /pepper_robot/camera/depth/image_raw --noarr 

header: 
  seq: 76
  stamp: 
    secs: 1442246921
    nsecs: 366206631
  frame_id: CameraDepth_optical_frame
height: 60
width: 80
encoding: 16UC1
is_bigendian: 0
step: 160

in my boot_config.json

```
"depth_camera":
{
  "enabled"       : true,
  "resolution"    : 2,
  "fps"           : 10,
  "recorder_fps"  : 10
},
```

everything works fine for resolution 1 (320x240)

**Comment by vrabaud** [comment]
Not supported on Pepper. A warning should probably be logged though.

**Comment by nlyubova** [comment]
@vrabaud do you know why it is not supported on Pepper? I can get VGA after few modifications in soft but I get low fps. Do you know what was the issue ?

**Comment by vrabaud** [comment]
That is to see with Corentin.

**Comment by nlyubova** [comment]
It is true @laurent-george  and it comes from Naoqi and not from Naoqi Driver. 
Seams impossible to solve, and the only possibility is to use QVGA or smaller

**Comment by mikaelarguedas** [comment]
I think that the warning suggested in https://github.com/ros-naoqi/naoqi_driver/issues/40#issuecomment-140737015 should be added to avoid confusion

**Comment by nlyubova** [comment]
@mikaelarguedas right, I never missed this comment

**Comment by warp1337** [comment]
When you look at the specs of the camera it indeed is capable of VGA. Can this be fixed in the NaoQi API?

**Comment by nlyubova** [comment]
The VGA is of worse quality than QVGA and this limitation comes from Naoqi but not from Naoqi Driver. Please, use QVGA.

**Comment by nlyubova** [comment]
@mikaelarguedas : please check https://github.com/ros-naoqi/naoqi_driver/pull/93
