### ISSUE TITLE
suggestion: adding /cmd_pose topic to naoqi_driver.launch

### ISSUE THREAD

**Issue by kochigami** [ros-naoqi/naoqi_driver#45]
When I executed  ```roslaunch pepper_bringup pepper_full.launch```, I found ```/cmd_vel``` topic, but I couldn't find ```/cmd_pose```.
I would like to have also ```/cmd_pose``` in ```naoqi_driver.launch```. Could you tell me what do you think?

In ```nao_walker.py``` in ```nao_robot/nao_apps/nodes``` (https://github.com/ros-naoqi/nao_robot/blob/master/nao_apps/nodes/nao_walker.py#L93), both topics are prepared.
There is one pull-request for pepper walking-related function, and it uses both topics. ([nao_robot package] add launch/nao_wheel.launch nodes/nao_wheel.py #13 )(https://github.com/ros-naoqi/nao_robot/pull/13)

**Comment by k-okada** [comment]
I think you can use `mobe_base_simple/goal` of https://github.com/ros-naoqi/naoqi_driver/blob/master/src/naoqi_driver.cpp#L789 instead of `cmd_pose`
