### ISSUE TITLE
bottom_cmaeraCmaera Handle is empty, and can not see front camer on rostopic, but we can see front camera on choregraph

### ISSUE THREAD

**Issue by k-okada** [ros-naoqi/naoqi_driver#57]
```
bottom_cameraMight be a NAOqi problem. Try to restart the ALVideoDevice.
bottom_cameraCamera Handle is empty - cannot retrieve image
bottom_cameraMight be a NAOqi problem. Try to restart the ALVideoDevice.
bottom_cameraCamera Handle is empty - cannot retrieve image
bottom_cameraMight be a NAOqi problem. Try to restart the ALVideoDevice.
bottom_cameraCamera Handle is empty - cannot retrieve image
bottom_cameraMight be a NAOqi problem. Try to restart the ALVideoDevice.
bottom_cameraCamera Handle is empty - cannot retrieve image
bottom_cameraMight be a NAOqi problem. Try to restart the ALVideoDevice.
^Cbottom_cameraCamera Handle is empty - cannot retrieve image
bottom_cameraMight be a NAOqi problem. Try to restart the ALVideoDevice.
``

**Comment by Karsten1987** [comment]
I was struggling with this error as well. I haven't seen a way to fix that on any ROS side. It seems to me that this situation occurs when there are zombie subscriber to the ALVideoDevice, which finally exceed the maximal number of subscribers.
@k-okada Can you somehow reproduce this behavior regularly? If so, please check the number of subscribers.

**Comment by suryaambrose** [comment]
@Karsten1987 you are right :).
This happens when you launch "something" that subscribes to a camera but does not unsubscribe. Launch this script 6 or 7 times and then this error happens. 

If you can reproduce this issue often, you are probably subscribing to a camera without unsubscribing afterwards.

**Comment by k-okada** [comment]
OK, I found that it does happens if we enable audio, which fail to call "unsubscribe" at https://github.com/ros-naoqi/naoqi_driver/blob/master/src/event/audio.cpp#L115 . Or to be more precise, it calls "unsubscribe" but never returns, whcn we type "C-c". Do you have any idea?
```
index a9e0bd3..e4182cd 100644
--- a/share/boot_config.json
+++ b/share/boot_config.json
@@ -72,7 +72,7 @@
     },
     "audio":
     {
-      "enabled"       : true
+      "enabled"       : false
     },
     "bumper":
     {
```

**Comment by k-okada** [comment]
should we call `subscribe` before `setClientPreferences` ? https://github.com/ros-naoqi/naoqi_driver/blob/master/src/event/audio.cpp#L95

**Comment by suryaambrose** [comment]
Seriously  O_o ?? I really don't see why audio would cause a camera issue. Can you provide a protocol to reproduce this issue please ?

For your second question, it is better to call setClientPreferences before subscribing so that is not the issue.

**Comment by k-okada** [comment]
if we enable audio, C-c did not work, so the ros process did not shutdown
cleanly, that'd did not unsubscribe the camera correctly, if we disable
audio, C-c works.

--
◉ Kei Okada

**Comment by suryaambrose** [comment]
Ok I understand. Maybe we should make another issue then ? This needs further investigation.

**Comment by k-okada** [comment]
sure, please confirm current master did not stop cleanly and create PR.

--
◉ Kei Okada
