### ISSUE TITLE
error 712 with Pepper

### ISSUE THREAD

**Issue by lengagne** [ros-naoqi/naoqi_driver#86]
Hi all,

I am using naoqi_driver to control the robot Pepper.

The use of naoqi_driver makes the error 712 when shutting down the robot.

Moreover, if no topic are sent to control the head, there is an issue.
The head angle is drifting and the telemeter sensor detects an object to close to move the robot (but there is no).

I am using ROS indigo 

can you help me to solve this issue ?

Sébastien

**Comment by nlyubova** [comment]
Right, it is a known issue of Naoqi rather than Naoqi Driver
